sudo: required
dist: trusty
language: ruby
services:
- docker
before_install:
- cd cevo-hugo
- docker pull ubuntu:16.04
script:
- docker-compose build alpha
- docker-compose run alpha
deploy:
  provider: s3
  access_key_id: AKIAISTVPZKRQRHZ4VRQ
  secret_access_key:
    secure: iIMBVFqI3QAZr/BJhNksPtn9cemN8InLwtZiWpF508+YzbK+yMa1lqRdqbQxNCmo23EPNo1ATj2cIUlXtlZ8+X0Gm+IjtOUWa/BYf0AjyICZqb0g4iEI3LYJBLY6i/gxSZiI0FLJyMQxQxViYK8jl/W8Dq+VPfvqoB4ggMIThgXLMK749P7Cqwrqeu32dPN5Mh7MqhdCuUVRZ7F3Ry7/4Z4MzTH76dJL55yZzNT8srDnkJ9Qm9A8chup4n9qGiwQ5c7Lb5PFTMzqgQeY9MU5ssDJ5jBXerVo9iHXueknLstttd5KufoYbJ+5wwrvn7rbjKvBYEP5BoJ9w0bL6B/OZLhmzQ+vuy8o0tC6kISh6gNzTwGQd4lzljLh+bNN7DNxv5hynLAaTvwX0npLkcvVLbiWuq6EY/CMeszbx56xWg/z6VdjCY6ALnbV2U874N9teHKgyFDZ7KK2AhwAxJbmN8KWuwgRGesGBJXSIiC9Nx7+F9KxVfh3y+FgQv79niehXPqbzw3hGkoQG/Qem5auCQP0EP7u5GOFVpMkeqWdnZhWDkYdgOUJkozQ+spNdlsUI3WhGyr9dp/LcXPBitGlQpedCkMwCvnxsCAr5OOgfRrywC1hXZSTHh17I9/ui+fTQh+r5jPSNKDcxew22ZJabmx5UbzlT4GStoR2oYoz7UY=
  region: ap-southeast-2
  local_dir: public
  bucket: new.cevo.com.au
  skip_cleanup: true
  acl: public_read
  on:
    branch: hugo-port
notifications:
  slack:
    secure: QiL7R6/ARch+1zek730zvWKoEtsHY73ftC5udpkpoyd2A/MWngTFnctvRrTa/rbqPJD/29VyZnWDHrAgskEBwecsBKJ+wRRBU8k96wmTE4tZoTcnWnWvfvAAmTZ6t8fCNZR+MHkH05gTSMU/l8rafao3TcEd4p6VaVH4VP9wtUA7DHeJQ5dh7DGAlg7rOCl/2N39YknVxhpkq6VOVCVq+z9aaJVX6BT+OBDrgsdN7ZpI2sJZo6T6/Z5s/KSLiL2l4lrhX4LB6cbGuY+saUwfNs2jdfvNYqjPofowoYmMpi6sip/4WxkIsEgUrJXi6wQ7aSbWuF+sFshZOSn36i2VFYsuiNbbWNL0pCl/jGFODu5f77rud/MDf4roQPg08rZEyL56QCiwsez2zYcXMK+iPCOzw2U+VWW9yT7WXG64QrquCiUY8vcy8OPMsRQj1x1hEBf/tIT7tC6XBe6leu4GwF212ZtXc6x0/3DJu76WZF4lB5IuIEmTGUtKNXqEA382vzQ5SY50onwEtlbZ7ozjcMh9OTQ7GDhZgD6qNCZ9MUN4FcTYiVdISK2rp85Z39irHMZ/l9lierdcaKpKuPcRY5oEk+y6N7ZB93rGnuf8YzHiY0SVcW3D1UicH5952P6Bq3ft7b5uVkRQMdZ3wjSJzGKZ0upbfPSe0dKZki/7jKQ=
