sudo: required
dist: trusty
language: ruby
services:
- docker
before_install:
- cd cevo-hugo
- docker pull ubuntu:16.04
script:
- docker-compose build alpha
- docker-compose run alpha
deploy:
  provider: s3
  access_key_id: AKIAJ6XEGHLGWPE3LALA
  secret_access_key:
    secure: DFK6Z8pqSqD8u2sVJTzKTc+fRlyEjQnuNZ2RlsuWNeYcIcaZbGrMajbdmOIkq1Zo8AaRdh6LSJ2PjxNlfA73j95NcpASMQYYKel2gc/5Ug/Xm5AIYxYyaM6J89zOyFyh3Yezrcg/75KfQw0UaOZbji5fXc04+R1fhnc1Ook8BcMuCv7XYSDLlWwe0Ksb970qM62SB0+Pp2cXm8jTSwtCNkl9cD+T59uLaJgvBBRNq55o7uOsHzqYwdfuINEUcFJfAlckDBPGHSeQsnq8dtEBvdOfVreqiQqmXkdHILyhhPAz8MqGk5qHo3kYurIXv4uD8bp+V/SZ95DPjCspbhLe+NbMzesp5qWPR9zmu7M/DVXajkNWBYGwUSs4R//d7tkY8sEWePC9nxUOauYeHBwNHRl+2298qZ8t6UwzvDdcAhirgoVtEUWYR28ytffgEAz+E5SEfjmoggVqoMbrRUAnq5Gs0yFcDIXG+Z2W8mYyKP/ZnCfq5On5kThOFutHcwitbiwO+bpk9C9uX0D2GO67pDWLq1c4WlKSSw+35YSkxjURSoiEctQGFRKjMTt0D02QHkrPrvMe7wWZFkmZJCbKWhp38giu3h37+fZnsyqlriMccxJQwVxA7Gf2N/8aB10TlMRJlLhoHakg3LzP5oott+QNzXnssbPP8pl/1HPtHWI=
  region: ap-southeast-2
  local_dir: public
  bucket: new-cevo-website
  skip_cleanup: true
  acl: public_read
  on:
    branch: hugo-port
notifications:
  slack:
    secure: QiL7R6/ARch+1zek730zvWKoEtsHY73ftC5udpkpoyd2A/MWngTFnctvRrTa/rbqPJD/29VyZnWDHrAgskEBwecsBKJ+wRRBU8k96wmTE4tZoTcnWnWvfvAAmTZ6t8fCNZR+MHkH05gTSMU/l8rafao3TcEd4p6VaVH4VP9wtUA7DHeJQ5dh7DGAlg7rOCl/2N39YknVxhpkq6VOVCVq+z9aaJVX6BT+OBDrgsdN7ZpI2sJZo6T6/Z5s/KSLiL2l4lrhX4LB6cbGuY+saUwfNs2jdfvNYqjPofowoYmMpi6sip/4WxkIsEgUrJXi6wQ7aSbWuF+sFshZOSn36i2VFYsuiNbbWNL0pCl/jGFODu5f77rud/MDf4roQPg08rZEyL56QCiwsez2zYcXMK+iPCOzw2U+VWW9yT7WXG64QrquCiUY8vcy8OPMsRQj1x1hEBf/tIT7tC6XBe6leu4GwF212ZtXc6x0/3DJu76WZF4lB5IuIEmTGUtKNXqEA382vzQ5SY50onwEtlbZ7ozjcMh9OTQ7GDhZgD6qNCZ9MUN4FcTYiVdISK2rp85Z39irHMZ/l9lierdcaKpKuPcRY5oEk+y6N7ZB93rGnuf8YzHiY0SVcW3D1UicH5952P6Bq3ft7b5uVkRQMdZ3wjSJzGKZ0upbfPSe0dKZki/7jKQ=
