sudo: required
dist: trusty
language: ruby
services:
- docker
before_install:
- cd cevo-hugo
- docker pull ubuntu:16.04
script:
- docker-compose build alpha
- docker-compose run alpha
deploy:
  provider: s3
  access_key_id: AKIAJ223OQAQ5VH7BE6A
  region: ap-southeast-2
  local_dir: public
  bucket: new.cevo.com.au
  skip_cleanup: true
  acl: public_read
  on:
    branch: hugo-port
  secret_access_key:
    secure: LO/B87PGt99ttousLzmRvH2Xm4cASEhUVb+ZtJzRwBLiwM24h/s3UG3B+JyluuU6H9tZzPxxdd41NRj0on5JRZgMtE7c2eC8N+yDZjT8jTXQzARrfO4ipY77P3+p8fl0TWCD9DSww6ROqFFwPMjpifvLGAUClerFDLGjJn2jXNkI094koiWvUXjMh/GdpJxhteWrmkpSMGA+FwFZ0ylR9Ga54sfiHnA1efP/Ith2QDdkFDCiNL5JAxUlrJQnY8IA74cd4YDmeNVXOsLSULYV3XocjnGeTeefunmBhNJ9xOUA8nNBQ57/VihwLbY/l2xV8x1ZOr+PXUY5hUYzTG+4uXTqSugJJ7ls2woHmGYiSBpeEat/f3OSLjAArFZqB9wL9Ukn1Pw7WHv/RFDHIzDT+4ldMfqHfF9Roo3MNpkRriETzvhlSF88uQg9VnwjIFbhnUyEyA7+oU9oyYCCGpdTAXdM8UbZG4DHk/KTm21jFLMVwZLdqEv+Ng6kLLqzFLvpwEOvjhSsZ1APGo8jav/+35ZucHfR967kw6wx4vbwA0n53O0gPS7CMsDN77c4qrT8Jyinw3GfTSXWz8KsNbw5XEbSpCalJpt7wd5TRONyB98sgy6KXVfXs7xQMaAPEBEpHvb2vz0kvvdWQYdxbgT2uW2ly1bokdPO6UmOypMGGMM=
notifications:
  slack:
    secure: QiL7R6/ARch+1zek730zvWKoEtsHY73ftC5udpkpoyd2A/MWngTFnctvRrTa/rbqPJD/29VyZnWDHrAgskEBwecsBKJ+wRRBU8k96wmTE4tZoTcnWnWvfvAAmTZ6t8fCNZR+MHkH05gTSMU/l8rafao3TcEd4p6VaVH4VP9wtUA7DHeJQ5dh7DGAlg7rOCl/2N39YknVxhpkq6VOVCVq+z9aaJVX6BT+OBDrgsdN7ZpI2sJZo6T6/Z5s/KSLiL2l4lrhX4LB6cbGuY+saUwfNs2jdfvNYqjPofowoYmMpi6sip/4WxkIsEgUrJXi6wQ7aSbWuF+sFshZOSn36i2VFYsuiNbbWNL0pCl/jGFODu5f77rud/MDf4roQPg08rZEyL56QCiwsez2zYcXMK+iPCOzw2U+VWW9yT7WXG64QrquCiUY8vcy8OPMsRQj1x1hEBf/tIT7tC6XBe6leu4GwF212ZtXc6x0/3DJu76WZF4lB5IuIEmTGUtKNXqEA382vzQ5SY50onwEtlbZ7ozjcMh9OTQ7GDhZgD6qNCZ9MUN4FcTYiVdISK2rp85Z39irHMZ/l9lierdcaKpKuPcRY5oEk+y6N7ZB93rGnuf8YzHiY0SVcW3D1UicH5952P6Bq3ft7b5uVkRQMdZ3wjSJzGKZ0upbfPSe0dKZki/7jKQ=
