sudo: required
dist: trusty
language: ruby
services:
- docker
before_install:
- cd cevo-hugo
- docker pull ubuntu:16.04
script:
- docker-compose build alpha
- docker-compose run alpha
deploy:
  provider: s3
  access_key_id: AKIAJOTYFRXUR7LFSCPA
  secret_access_key:
    secure: yl/znvHMq3N9vsWbWZAsxoxWAYu9cMwhaEQDyQmsYripcJYQj/MdMM7ZI9LrfLbpEZq1YiT/5cSF4H8MX35sB2JOjvgM/HjZi5jHtccuLfJ3E/XubE3plZz/P/JTLhI3GvdFskLT75auneH8CFD2OH8445Pabm1vhJcJ5lHbsX8JW+TnMfopvkZLaLjL3NtgxX8bqqesWYBVfN85NIdFCKyxfjCrLpLS3xsV/6fw9TL+Pwb5v+4091VwYGtDcn+IZeEEr7Kg8XaYL3/L3R1i9e1PGcKnp3ouB7M70Z8LD6NpgrKcuGI/MocCYGMJ28Bte99xLXMYuXLTCHmuqj9WmcnKnLRow7dfpTwGnhbBcqUK/Vekn2Idg3x2WEDdF7Bmdaz9kIhZizegA9oZhczdv02coPYclxzTZh6sPoUG8nUIWELe+8WH+QZo5k5cAoAu0Y9/ntqeyDf970TnS+GUGSWal8eG4O2sQgOIVuBV5KNZAv0jq5iuLI8O93GTS4v4Qr+g547j599X3oC+cPk7Vn6bXi0WhTWejeOo2lQrskQLqTaGiAdemzig2gPwG08d8HRc6q/zgR0yamjBf9MCENP2dbGUFAUZRB9Axq2CgW6WZWSo259G+qv+HWhY/y37tIV0ogdXSKGULt4RlHZJgco5k96Y7EIWgdR3sWA03B4=
  region: ap-southeast-2
  local_dir: public
  bucket: cevo-hugo
  skip_cleanup: true
  acl: public_read
  on:
    branch: hugo-port
