# Site settings
title: Cevo
email: sales@cevo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Cevo
  Software Consulting
  Devops
  Automation
  Infrastructure
baseurl: "" # the subpath of your site, e.g. /blog/
# URL configuration is managed at build time through the use of _config_<ENV>.yml files
# url: "https://www.cevo.com.au" # the base hostname & protocol for your site
twitter_url: https://twitter.com/cevoaustralia
linkedin_url: https://www.linkedin.com/company/cevoaustralia
youtube_url: https://www.youtube.com/channel/UCeWwnMuG8a93Y5jf3ak2HIw
melbourne_address: Level 14, 303 Collins St, Melbourne VIC 3000
sydney_address: Level 4, 20 Bond Street, Sydney NSW 2000

sales:
  phone: 1300 518 265
  email: sales@cevo.com.au

careers:
  phone: 1300 518 265
  email: careers@cevo.com.au

# Build settings
exclude: [Gemfile, Gemfile.lock, README.md, TODO.md, .dockerignore, install_image_optim.sh]
markdown: kramdown
plugins: [jekyll-paginate, jekyll-assets]
paginate: 4
paginate_path: "blog/page:num"
future: true
host: 0.0.0.0


kramdown:
  input: GFM
  syntax_highlighter: rouge

assets:
  digest: true
  compress:
    css: sass
    js: uglifier
  sources:
    - _assets/css
    - _assets/javascripts
    - _assets/images
