# Site settings
title: Cevo
email: sales@cevo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Cevo site.
  Under construction.
  Software Consulting
  Devops
  Automation
  Infrastructure
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_url: https://twitter.com/cevoaustralia
linkedin_url: https://www.linkedin.com/company/cevoaustralia
sydney_address: Level 4, 2-12 Foveaux St, Surry Hills NSW 2010
melbourne_address: Level 14, 303 Collins St, Melbourne VIC 3000
sales:
  phone: 1300 518 265
  email: sales@cevo.com.au

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 4
paginate_path: "blog/page:num"
