- icon_class: fa fa-dot-circle-o
  title: Software Delivery
  desc:
    To deliver new
    concepts and solutions, organisations need the
    ability to rapidly deploy code to production, and iterate based on
    customer feedback.
  link: services.html#software
# - icon_class: fa fa-trophy
#   title: Design
#   desc:
#     We assist organisations build immutable platforms, combining innovative automation technologies with unparalleled engineering skills.
#   further-reading:
#   image:
- icon_class: fa fa-compass
  title: DevOps
  desc:
    We help you build, manage, and optimise your continuous deployment pipeline, from source control through testing to automated production releases.
  link: services.html#devops
  image:
- icon_class: fa fa-star-half-empty
  title: Automation
  desc:
    We assist organisations to build immutable infrastructure platforms, combining innovative automation technologies with unparalleled engineering skills.
  link: services.html#automation
