- icon_class: fa fa-dot-circle-o
  title: Agile
  desc:
    To deliver new
    concepts and solutions, organisations need the
    ability to rapidly deploy code to production, and iterate based on
    customer feedback.
  link: services.html#software
- icon_class: fa fa-compass
  title: DevOps
  desc:
    We help you build, manage, and optimise your continuous deployment pipeline, from source control through testing to automated production releases.
  link: services.html#devops
- icon_class: fa fa-star-half-empty
  title: Automation
  desc:
    We assist organisations to build immutable infrastructure platforms, combining innovative automation technologies with unparalleled engineering skills.
  link: services.html#automation

- icon_class: fa fa-cogs
  title: Engineering
  desc: >
    Software engineering is a skill of balancing possibilities, skills and tools to achive desired state of of your systems.
  link: services.html#engineering
